### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by davidkslack** [nitrado/Nitrapi#1]
Hi,

I'm looking to start a Windows 10 App using your API but not sure how to get an access token, you say:
"For using the NITRAPI you need as first setup a new application. Please go to https://server.nitrado.net and login to your own nitrado.net user account. After you are logged in please register a own application at the developer area."

I don't see a developer area and https://server.nitrado.net/eng/developer/applications only shows the applications I don't have!

Can you help?
What am I missing?

Thanks
Dave.

**Comment by BirknerAlex** [comment]
Hello David,

please post your Nitrado user id. Your account needs to be enabled for the Nitrapi Beta. After your activation you are able to add new applications. You will receive a client id and client secret after this. 

Please use this documentation http://nitrado.github.io/Nitrapi/oauth/ to use the oAuth endpoint for authentication. After a successful oAuth login you will receive a valid access token.

Notice: For oAuth2 on a native application instead of a web application your app needs to register a uri scheme on the operating system to use the redirect url. It's a little bit tricky.

Regards,
Alexander

**Comment by davidkslack** [comment]
Hi Alexander,

My User ID is 795909
I've used oAuth before with the 3 legged auth so hopefully it won't cause too much of an issue; thanks for the heads up though.

Not sure how far I'll get on this little project, but I'll see what I can do.

Cheers
Dave.

**Comment by BirknerAlex** [comment]
Your account has been activated for the Nitrapi Beta.

Have fun. :)

**Comment by davidkslack** [comment]
Thanks Alexander, looking forward to playing with this!

**Comment by kayzore** [comment]
Hi

I want to acces to your Nitrapi to manage my servers via a custom website.
But... I don't find any documentation to sign in. You always need to manually activate account ?

Thanks
Kayzore.

**Comment by f0086** [comment]
@kayzore You need a access token to use the NitrAPI endpoints. To get one, you need to do one of the following things:

* Use the OAuth-Flow to login and gather a access/refresh-token. I've wrote a tutorial how to do that here (german): https://aaron-fischer.net/wae There are also a log of libs available who handle the oauth flow for you.
* Generate a long life token and use that. Go to nitrado.net, login, "My Account", "Developer Portal", "Long-Life Tokens" (top right corner)
